### PR TITLE
OC-14 join event button

### PR DESCRIPTION
**Pull request by MSO03**
Renamed all posts to events for clarity

### CODE REVIEW

**Review by nverkhachoyan — APPROVED** [review]
Nice changes, but we should consider regular posts as well, not every user is gonna post an Event

**Comment by MSO03** [comment]
By regular posts, do you mean comments to specific events?

**Comment by nverkhachoyan** [comment]
No, think of it like Twitter, there are regular posts people can make to make the website more interactive and engaging, and there will be club admins that can make actual Events. There aren't many events happening that often, so it would be dry otherwise.

**Comment by MSO03** [comment]
Oh ok, that's a good idea.

**Pull request merged**
